/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.64
 * Generated at: 2023-07-17 05:46:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import connectionDB.*;
import java.sql.*;

public final class ViewStation_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"utf-8\">\r\n");
      out.write("    <title>EV Charge Station</title>\r\n");
      out.write("    <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("    <meta content=\"\" name=\"keywords\">\r\n");
      out.write("    <meta content=\"\" name=\"description\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Favicon -->\r\n");
      out.write("    <link href=\"img/favicon.ico\" rel=\"icon\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Google Web Fonts -->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Open+Sans:wght@400;600&family=Roboto:wght@500;700&display=swap\" rel=\"stylesheet\"> \r\n");
      out.write("    \r\n");
      out.write("    <!-- Icon Font Stylesheet -->\r\n");
      out.write("    <link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Libraries Stylesheet -->\r\n");
      out.write("    <link href=\"lib/owlcarousel/assets/owl.carousel.min.css\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"lib/tempusdominus/css/tempusdominus-bootstrap-4.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("\r\n");
      out.write("    <!-- Customized Bootstrap Stylesheet -->\r\n");
      out.write("    <link href=\"css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Stylesheet -->\r\n");
      out.write("    <link href=\"css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("        <!-- Spinner Start -->\r\n");
      out.write("        <div id=\"spinner\" class=\"show bg-dark position-fixed translate-middle w-100 vh-100 top-50 start-50 d-flex align-items-center justify-content-center\">\r\n");
      out.write("            <div class=\"spinner-border text-primary\" style=\"width: 3rem; height: 3rem;\" role=\"status\">\r\n");
      out.write("                <span class=\"sr-only\">Loading...</span>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Spinner End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Sidebar Start -->\r\n");
      out.write("        <div class=\"sidebar pe-4 pb-3\">\r\n");
      out.write("            <nav class=\"navbar bg-secondary navbar-dark\">\r\n");
      out.write("                <a href=\"index.html\" class=\"navbar-brand mx-4 mb-3\">\r\n");
      out.write("                    <h3 class=\"text-primary\"><i class=\"fa fa-user-edit me-2\"></i>\"ElectriPort<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Plaza\"</h3>\r\n");
      out.write("                </a>\r\n");
      out.write("                <div class=\"d-flex align-items-center ms-4 mb-4\">\r\n");
      out.write("                    <div class=\"position-relative\">\r\n");
      out.write("                        <img class=\"rounded-circle\" src=\"img/user.jpg\" alt=\"\" style=\"width: 40px; height: 40px;\">\r\n");
      out.write("                        <div class=\"bg-success rounded-circle border border-2 border-white position-absolute end-0 bottom-0 p-1\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"ms-3\">\r\n");
      out.write("                        <h6 class=\"mb-0\">PowerHub</h6>\r\n");
      out.write("                        <span>Admin</span>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("               <div class=\"navbar-nav w-100\">\r\n");
      out.write("                    <a href=\"index.html\" class=\"nav-item nav-link active\"><i class=\"fa fa-tachometer-alt me-2\"></i>Home</a>\r\n");
      out.write("                    <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-laptop me-2\"></i>Admin</a>\r\n");
      out.write("                        <div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("                        <a href=\"login.html\" class=\"nav-item nav-link active\">Login</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-laptop me-2\"></i>Charging Station</a>\r\n");
      out.write("                        <div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("                        \t<a href=\"loginstation.html\" class=\"nav-item nav-link active\">Log Out</a>\r\n");
      out.write("                        \t <ul>\r\n");
      out.write("\t\t\t\t\t\t        <li><a href=\"LoginStation?action1=ViewStation\">View Charging Station</a></li>\r\n");
      out.write("\t\t\t\t\t\t        <li><a href=\"LoginStation?action1=UpdatePowerServlet\">Update Charging Station Power</a></li>\r\n");
      out.write("\t\t\t\t\t\t \t</ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                      <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\"><i class=\"fa fa-laptop me-2\"></i>User</a>\r\n");
      out.write("                        <div class=\"dropdown-menu bg-transparent border-0\">\r\n");
      out.write("                        \t<a href=\"loginstation.html\" class=\"nav-item nav-link active\">Log Out</a>\r\n");
      out.write("                        \t <ul>\r\n");
      out.write("\t\t\t\t\t\t        <li><a href=\"UserLoginServlet?action2=ViewStation\">View Charging Station</a></li>\r\n");
      out.write("\t\t\t\t\t\t \t</ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Sidebar End -->\r\n");
      out.write("<style>\r\n");
      out.write("#customers {\r\n");
      out.write("  font-family: \"Trebuchet MS\", Arial, Helvetica, sans-serif;\r\n");
      out.write("  border-collapse: collapse;\r\n");
      out.write("  width: 100%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#customers td, #customers th {\r\n");
      out.write("  border: 1px solid #ddd;\r\n");
      out.write("  padding: 8px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#customers tr:nth-child(even){background-color: #f2f2f2;}\r\n");
      out.write("\r\n");
      out.write("#customers tr:hover {background-color: #ddd;}\r\n");
      out.write("\r\n");
      out.write("#customers th {\r\n");
      out.write("  padding-top: 12px;\r\n");
      out.write("  padding-bottom: 12px;\r\n");
      out.write("  text-align: left;\r\n");
      out.write("  background-color: #4CAF50;\r\n");
      out.write("  color: white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("        <!-- Content Start -->\r\n");
      out.write("        <div class=\"content\">\r\n");
      out.write("            <!-- Navbar Start -->\r\n");
      out.write("            <nav class=\"navbar navbar-expand bg-secondary navbar-dark sticky-top px-4 py-0\">\r\n");
      out.write("                <a href=\"index.html\" class=\"navbar-brand d-flex d-lg-none me-4\">\r\n");
      out.write("                    <h2 class=\"text-primary mb-0\"><i class=\"fa fa-user-edit\"></i></h2>\r\n");
      out.write("                </a>\r\n");
      out.write("                <a href=\"#\" class=\"sidebar-toggler flex-shrink-0\">\r\n");
      out.write("                    <i class=\"fa fa-bars\"></i>\r\n");
      out.write("                </a>\r\n");
      out.write("                <form class=\"d-none d-md-flex ms-4\">\r\n");
      out.write("                <script>\r\n");
      out.write("\t\t\t\t    function searchWithinPage() {\r\n");
      out.write("\t\t\t\t      var searchText = document.getElementById(\"searchText\").value;\r\n");
      out.write("\t\t\t\t      if (searchText) {\r\n");
      out.write("\t\t\t\t        if (window.find && window.getSelection) {\r\n");
      out.write("\t\t\t\t          document.designMode = \"on\";\r\n");
      out.write("\t\t\t\t          var sel = window.getSelection();\r\n");
      out.write("\t\t\t\t          sel.collapse(document.body, 0);\r\n");
      out.write("\t\t\t\t          while (window.find(searchText)) {\r\n");
      out.write("\t\t\t\t            document.execCommand(\"HiliteColor\", false, \"yellow\");\r\n");
      out.write("\t\t\t\t            sel.collapseToEnd();\r\n");
      out.write("\t\t\t\t          }\r\n");
      out.write("\t\t\t\t          document.designMode = \"off\";\r\n");
      out.write("\t\t\t\t        } else if (document.body.createTextRange) {\r\n");
      out.write("\t\t\t\t          var textRange = document.body.createTextRange();\r\n");
      out.write("\t\t\t\t          while (textRange.findText(searchText)) {\r\n");
      out.write("\t\t\t\t            textRange.execCommand(\"BackColor\", false, \"yellow\");\r\n");
      out.write("\t\t\t\t            textRange.collapse(false);\r\n");
      out.write("\t\t\t\t          }\r\n");
      out.write("\t\t\t\t        }\r\n");
      out.write("\t\t\t\t      }\r\n");
      out.write("\t\t\t\t    }\r\n");
      out.write("\t\t\t\t  </script>\r\n");
      out.write("                    <input class=\"form-control bg-dark border-0\" type=\"text\" id=\"searchText\" placeholder=\"Enter text to search\">\r\n");
      out.write("  \t\t\t\t\t<button onclick=\"searchWithinPage()\">Search</button>\r\n");
      out.write("                </form>\r\n");
      out.write("                <div class=\"navbar-nav align-items-center ms-auto\">\r\n");
      out.write("                     <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                            <i class=\"fa fa-envelope me-lg-2\"></i>\r\n");
      out.write("                            <span class=\"d-none d-lg-inline-flex\">Revived</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <img class=\"rounded-circle\" src=\"img/user.jpg\" alt=\"\" style=\"width: 40px; height: 40px;\">\r\n");
      out.write("                                    <div class=\"ms-2\">\r\n");
      out.write("                                        <h6 class=\"fw-normal mb-0\">\"Stay charged, stay on the go!\"</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <img class=\"rounded-circle\" src=\"img/user.jpg\" alt=\"\" style=\"width: 40px; height: 40px;\">\r\n");
      out.write("                                    <div class=\"ms-2\">\r\n");
      out.write("                                        <h6 class=\"fw-normal mb-0\">\"Powering up for your next adventure.\"</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <div class=\"d-flex align-items-center\">\r\n");
      out.write("                                    <img class=\"rounded-circle\" src=\"img/user.jpg\" alt=\"\" style=\"width: 40px; height: 40px;\">\r\n");
      out.write("                                    <div class=\"ms-2\">\r\n");
      out.write("                                        <h6 class=\"fw-normal mb-0\">\"Recharging your ride for a greener tomorrow.\"</h6>\r\n");
      out.write("                                    </div>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"https://ackodrive.com/ev-guide/ev-charging-safety-tips/\" class=\"dropdown-item text-center\">See all Revived Message</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                            <i class=\"fa fa-bell me-lg-2\"></i>\r\n");
      out.write("                            <span class=\"d-none d-lg-inline-flex\">Precaution Notifications</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <h6 class=\"fw-normal mb-0\">Avoid charging in severe weather.</h6>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <h6 class=\"fw-normal mb-0\">Properly unplug and stow the charging cable.</h6>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"#\" class=\"dropdown-item\">\r\n");
      out.write("                                <h6 class=\"fw-normal mb-0\">Keep your charging port clean</h6>\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <hr class=\"dropdown-divider\">\r\n");
      out.write("                            <a href=\"https://ackodrive.com/ev-guide/ev-charging-safety-tips/\" class=\"dropdown-item text-center\">See all Precaution notifications</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"nav-item dropdown\">\r\n");
      out.write("                        <a href=\"#\" class=\"nav-link dropdown-toggle\" data-bs-toggle=\"dropdown\">\r\n");
      out.write("                            <img class=\"rounded-circle me-lg-2\" src=\"img/user.jpg\" alt=\"\" style=\"width: 40px; height: 40px;\">\r\n");
      out.write("                            <span class=\"d-none d-lg-inline-flex\">PowerHub Incharge</span>\r\n");
      out.write("                        </a>\r\n");
      out.write("                        <div class=\"dropdown-menu dropdown-menu-end bg-secondary border-0 rounded-0 rounded-bottom m-0\">\r\n");
      out.write("                            <a href=\"profile.html\" class=\"dropdown-item\">My Profile</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <!-- Navbar End -->\r\n");
      out.write("\t\t\t<!-- Sale & Revenue Start -->\r\n");
      out.write("            <div class=\"container-fluid pt-4 px-4\">\r\n");
      out.write("                <div class=\"row g-4\">\r\n");
      out.write("                    <div class=\"col-sm-20 col-xl-15\">\r\n");
      out.write("                        <div class=\"bg-secondary rounded d-flex align-items-center justify-content-between p-4\">\r\n");
      out.write("                            <i class=\"fa fa-chart-line fa-3x text-primary\"></i>\r\n");
      out.write("                            <div class=\"ms-3\">\r\n");
      out.write("                                <h1 class=\"mb-2\"><center>ELECTRIC VEHICLE RECHARGE STATION FINDER</center></h1>\r\n");
      out.write("                                <h6 class=\"mb-0\">System</h6>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            \r\n");
      out.write("            <!-- Sliding Img Start-->\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"container-fluid pt-4 px-4\">\r\n");
      out.write("                <div class=\"bg-secondary text-center rounded p-4\">\r\n");
      out.write("                    <div class=\"d-flex align-items-center justify-content-between mb-4\">\r\n");
      out.write("                        <h3 class=\"mb-0\"><u><i>\"Clean Energy, Endless Journeys.\"</i></u></h3>\r\n");
      out.write("\t\t\t\t\t\t<hr>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"container-fluid pt-4 px-4\">\r\n");
      out.write("                        <h3>\"Charge with Confidence, Drive with Pride.\"</h3>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<div style=\"max-width:100%\">\r\n");
      out.write("\t  \t\t\t<img class=\"mySlides\"  src=\"EVCS.jpg\" width=1000 height=500 border=20>\r\n");
      out.write("\t  \t\t\t<img class=\"mySlides\"  src=\"ev3.jpg\" width=1000 height=500 border=20>\r\n");
      out.write("\t   \t\t\t<img class=\"mySlides\"  src=\"ev4.jpeg\" width=1000 height=500 border=20>\r\n");
      out.write("\t   \t\t\t<img class=\"mySlides\"  src=\"ev6.png\" width=1000 height=500 border=20>\r\n");
      out.write("\t   \t\t\t<img class=\"mySlides\"  src=\"ev.png\" width=1000 height=500 border=20>\r\n");
      out.write("\t   \t\t\t<img class=\"mySlides\"  src=\"ev5.png\" width=1000 height=500 border=20>\r\n");
      out.write("\t   \t\t\t<img class=\"mySlides\"  src=\"ev2.jpeg\" width=1000 height=500 border=20>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<script>\r\n");
      out.write("\t\t\t\tvar myIndex = 0;\r\n");
      out.write("\t\t\t\tcarousel();\r\n");
      out.write("\t\t\t\tfunction carousel() {\r\n");
      out.write("\t    \t\tvar i;\r\n");
      out.write("\t\t\t    var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("\t    \t\tfor (i = 0; i < x.length; i++) {\r\n");
      out.write("\t       \t\tx[i].style.display = \"none\";  \r\n");
      out.write("\t    \t\t}\r\n");
      out.write("\t    \t\tmyIndex++;\r\n");
      out.write("\t\t\t    if (myIndex > x.length) {myIndex = 1}    \r\n");
      out.write("\t\t\t    x[myIndex-1].style.display = \"block\";  \r\n");
      out.write("\t\t\t    setTimeout(carousel, 1000); // Change image every 2 seconds\r\n");
      out.write("\t\t\t\t}\t\r\n");
      out.write("\t\t\t\t</script>\r\n");
      out.write("           \t\t </div>\r\n");
      out.write("               </div>\r\n");
      out.write("            </div>\r\n");
      out.write("          <!-- Sliding Img End-->\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            <!-- Sale & Revenue End -->\r\n");
      out.write(" <div class=\"container-fluid\">\r\n");
      out.write("            <div class=\"row h-100 align-items-left justify-content-left\" style=\"min-height: 100vh;\">\r\n");
      out.write("                <div class=\"col-15 col-sm-8 col-md-6 col-lg-6 col-xl-6\">\r\n");
      out.write("                    <div class=\"bg-secondary rounded p-4 p-sm-5 my-4 mx-3\">\r\n");
      out.write("                        <div class=\"d-flex align-items-left justify-content-between mb-3\">\r\n");
      out.write("                            <h3>View Charging Stations</h3>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"form-body\">\r\n");
      out.write("\t                         <form action=\"ViewStation.jsp\"> \r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control\" id=\"floatingInput\" name=\"city\" placeholder=\"text\" required=\"\">\r\n");
      out.write("\t                            <label for=\"floatingInput\">Enter Station City</label>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                       \t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control\" id=\"floatingInput\" name=\"taluka\" placeholder=\"text\" required=\"\">\r\n");
      out.write("\t                            <label for=\"floatingInput\">Enter Station Taluka</label>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t                      \t<div class=\"form-floating mb-3\">\r\n");
      out.write("\t                            <input type=\"text\" class=\"form-control\" id=\"floatingInput\" name=\"district\" placeholder=\"text\" required=\"\">\r\n");
      out.write("\t                            <label for=\"floatingInput\">Enter Station District</label>\r\n");
      out.write("\t                        </div>\r\n");
      out.write("\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">Search</button>\r\n");
      out.write("\t\t\t\t\t\t\t</form> \r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\r\n");
      out.write("    \t");

					String city1 = request.getParameter("city");
	                String taluka1 = request.getParameter("taluka");
	               	String district1 = request.getParameter("district");	                            		
					if(city1!=null&&taluka1!=null&&district1!=null)
					{
					
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t\t\t\t\t\t<div class=\"progressbar-heading grids-heading\">\r\n");
      out.write("\t\t\t\t\t\t\t<h2>View Charging Station</h2>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div class=\"panel panel-widget forms-panel\">\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t<table id=\"customers\">\r\n");
      out.write("\t\t\t\t\t\t\t  <thead>\r\n");
      out.write("\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t    <tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>ID</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Station Name</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Address</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>City</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Taluka</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>District</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Opening Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Closing Time</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Mobile Number</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Latitude</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Longitude</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Password</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Power</th>\r\n");
      out.write("\t\t\t\t\t\t\t\t<th>Status</th>\r\n");
      out.write("\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t  </thead>\r\n");
      out.write("\t\t\t\t\t\t\t  \r\n");
      out.write("\t\t\t\t\t\t\t   <tbody>\r\n");
      out.write("\t\t\t\t\t\t\t  ");

							  	try
							  	{
							  		Connection con = MysqlCon.getCon();
							  		PreparedStatement ps = con.prepareStatement("select * from register_cs where city=? AND taluka=? AND district=? ");
							  		ps.setString(1, city1);
							  		ps.setString(2, taluka1);
							  		ps.setString(3, district1);
							  		ResultSet rs = ps.executeQuery();
							  		while(rs.next())
							  		{
							  		
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t  \t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t     <td>");
      out.print(rs.getInt(1));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(2));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(3));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(4));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(5));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(6));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(7));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(8));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(9));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(10));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(11));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(12));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(13));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t      <td>");
      out.print(rs.getString(14));
      out.write("</td>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t    </tr>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

							  		}
							  	}
							  	catch(Exception e)
							  	{
							  		e.printStackTrace();
							  	}
							  
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t \t    \r\n");
      out.write("\t\t\t\t\t\t\t  </tbody>\r\n");
      out.write("\t\t\t\t\t\t\t</table>\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t");

					}
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("   \t\t\r\n");
      out.write("           <!-- Footer Start -->\r\n");
      out.write("            <div class=\"container-fluid pt-4 px-4\">\r\n");
      out.write("                <div class=\"bg-secondary rounded-top p-4\">\r\n");
      out.write("                    <div class=\"row\">\r\n");
      out.write("                        <div class=\"col-12 col-sm-6 text-center text-sm-start\">\r\n");
      out.write("                            &copy; <a href=\"http://localhost:8080/EV_Charging_Station_Finder/\">EV Charger Finder</a>, All Right Reserved. \r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-12 col-sm-6 text-center text-sm-end\">\r\n");
      out.write("                            <!--/*** This template is free as long as you keep the footer authorâs credit link/attribution link/backlink. If you'd like to use the template without the footer authorâs credit link/attribution link/backlink, you can purchase the Credit Removal License from \"https://htmlcodex.com/credit-removal\". Thank you for your support. ***/-->\r\n");
      out.write("                            Designed By: <a href=\"https://htmlcodex.com\">G-10</a>\r\n");
      out.write("                            <br>Distributed By: <a href=\"https://themewagon.com\" target=\"_blank\">r3sys</a>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Footer End -->\r\n");
      out.write("        </div>\r\n");
      out.write("        <!-- Content End -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <!-- Back to Top -->\r\n");
      out.write("        <a href=\"#\" class=\"btn btn-lg btn-primary btn-lg-square back-to-top\"><i class=\"bi bi-arrow-up\"></i></a>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- JavaScript Libraries -->\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.4.1.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/chart/chart.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/easing/easing.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/waypoints/waypoints.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/owlcarousel/owl.carousel.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/moment-timezone.min.js\"></script>\r\n");
      out.write("    <script src=\"lib/tempusdominus/js/tempusdominus-bootstrap-4.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("    <!-- Template Javascript -->\r\n");
      out.write("    <script src=\"js/main.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
